Maintenance PR
ansible-collections/splunk.es pull request #67
Opened 2024-03-08 07:55 UTC by roverflow

##### SUMMARY

Uses [https://github.com/ansible/ansible-content-actions](https://github.com/ansible/ansible-content-actions)

##### ISSUE TYPE

- CI Pull Request

##### ADDITIONAL INFORMATION

```paste below
ack -> check_label
push -> draft_release ( manual only )
```

2024-03-08 08:19 UTC, Ruchip16 approved these changes

2024-03-08 08:23 UTC, KB-perByte requested changes

2024-03-08 08:23 UTC, KB-perByte commented on requirements.txt
> +paramiko
why?

2024-03-08 08:23 UTC, KB-perByte commented on .github/workflows/tests.yml
> +      - ansible-lint
needs unit source too!

2024-03-08 08:23 UTC, KB-perByte commented on .github/workflows/draft_release.yml
> +  COLLECTION_NAME: ios
this to be updated

2024-03-08 08:23 UTC, KB-perByte commented on .ansible-lint
> +# exclude_paths:
can remove! no need to comment it out!

2024-03-20 06:21 UTC, Ruchip16 commented on test-requirements.txt
>  flake8
i think flake8 should be removed from here as well

2024-03-20 06:30 UTC, Ruchip16 commented on mypy.ini
> +[mypy-ansible_collections.cisco.ios.*]
instead of `cisco.ios` it should be` [mypy-ansible_collections.splunk.es.*]`

2024-03-21 07:38 UTC, NilashishC approved these changes

2024-03-26 11:46 UTC, merged